### ISSUE TITLE
does not build because of unmatched "!app/main.css"

### ISSUE THREAD

**Issue by tcurdt** [mlunoe/react-bb-broccoli#4]
```
Error: Path or pattern "!app/main.css" did not match any files
  at Object.multiGlob (/Users/tcurdt/Downloads/react-bb-broccoli-master/node_modules/broccoli-concat/node_modules/broccoli-kitchen-sink-helpers/index.js:203:13)
  at /Users/tcurdt/Downloads/react-bb-broccoli-master/node_modules/broccoli-concat/index.js:62:32
  at lib$rsvp$$internal$$tryCatch (/Users/tcurdt/Downloads/react-bb-broccoli-master/node_modules/broccoli/node_modules/rsvp/dist/rsvp.js:489:16)
  at lib$rsvp$$internal$$invokeCallback (/Users/tcurdt/Downloads/react-bb-broccoli-master/node_modules/broccoli/node_modules/rsvp/dist/rsvp.js:501:17)
  at lib$rsvp$$internal$$publish (/Users/tcurdt/Downloads/react-bb-broccoli-master/node_modules/broccoli/node_modules/rsvp/dist/rsvp.js:472:11)
  at lib$rsvp$asap$$flush (/Users/tcurdt/Downloads/react-bb-broccoli-master/node_modules/broccoli/node_modules/rsvp/dist/rsvp.js:1290:9)
  at process._tickCallback (node.js:355:11)
```

**Comment by mlunoe** [comment]
I did explore this a little and it seems that the globbing doesn't work properly. I will look into a solution, when I do get some time. For now you can change these lines:
```
    cssTree = concatCSS(cssTree, {
      inputFiles: [
        "**/*.css",
        "!" + dirs.stylesDist + "/" + fileNames.mainStyles + ".css",
        dirs.stylesDist + "/" + fileNames.mainStyles + ".css"
      ],
      outputFile: "/" + dirs.stylesDist + "/application.css",
    });
```

to this:
```
    cssTree = concatCSS(cssTree, {
      inputFiles: ["**/*.css"],
      outputFile: "/" + dirs.stylesDist + "/application.css",
    });
```

Though you will loose control over the order that files are included, as they will be included alphabetically.

Hope this helps for now.

**Comment by mlunoe** [comment]
Fixed by: https://github.com/mlunoe/react-bb-broccoli/pull/102
